### ISSUE TITLE
分表情况下max 结果集未进行聚合取最大值

### ISSUE THREAD

**Issue by peteringz** [xuejmnet/ShardingConnector#10]
以下是示例代码

            var dbConnection = dataSource.CreateConnection();

            var dbCommand = dbConnection.CreateCommand();
            dbCommand.CommandText = "select MAX(Age) AS max_age from SysUserMod where Id  in (@p1,@p2,@p3,@p4)";

            var dbParameter = dbCommand.CreateParameter();
            dbParameter.ParameterName = "@p1";
            dbParameter.Value = "21";
            var dbParameter2 = dbCommand.CreateParameter();
            dbParameter2.ParameterName = "@p2";
            dbParameter2.Value = "19";
            var dbParameter3 = dbCommand.CreateParameter();
            dbParameter3.ParameterName = "@p3";
            dbParameter3.Value = "14";
            var dbParameter4 = dbCommand.CreateParameter();
            dbParameter4.ParameterName = "@p4";
            dbParameter4.Value = "155";

            dbCommand.Parameters.Add(dbParameter);
            dbCommand.Parameters.Add(dbParameter2);
            dbCommand.Parameters.Add(dbParameter3);
            dbCommand.Parameters.Add(dbParameter4);
            var dbDataReader = dbCommand.ExecuteReader();

**Comment by xuejmnet** [comment]
已修复
